export const forumPosts = [
  {
    id: 1,
    title: "How to solve Two Sum problem efficiently?",
    author: "alex_coder",
    category: "Algorithms",
    replies: 15,
    views: 234,
    lastActivity: "2 hours ago",
    tags: ["arrays", "hash-table", "easy"],
  },
  {
    id: 2,
    title: "Understanding Dynamic Programming",
    author: "maria_dev",
    category: "Data Structures",
    replies: 8,
    views: 156,
    lastActivity: "5 hours ago",
    tags: ["dp", "algorithms", "medium"],
  },
  {
    id: 3,
    title: "Best practices for React performance",
    author: "john_algorithm",
    category: "Frontend",
    replies: 23,
    views: 445,
    lastActivity: "1 day ago",
    tags: ["react", "performance", "frontend"],
  },
  {
    id: 4,
    title: "System Design: Designing a URL Shortener",
    author: "system_designer",
    category: "System Design",
    replies: 31,
    views: 567,
    lastActivity: "3 hours ago",
    tags: ["system-design", "scalability", "database"],
  },
  {
    id: 5,
    title: "Graph Algorithms: BFS vs DFS",
    author: "graph_master",
    category: "Algorithms",
    replies: 19,
    views: 289,
    lastActivity: "6 hours ago",
    tags: ["graphs", "bfs", "dfs", "algorithms"],
  },
];
