#!/usr/bin/env sh
echo "Running ESLint and Prettier..."

npm run format

npm run lint
lint_status=$?

if [ $lint_status -ne 0 ]; then

    echo "ESLint found issues. Please fix them before committing."

  exit 1
fi

echo "✅ Everything is fine, no lint or formatting issues found!"
